nome = str(input('Digite seu nome completo:')).strip()
print('Muito prazer em te conhecer!!')
nomen = nome.split()
#print(nomen)
print('Seu primeiro nome é {}'.format(nomen[0]))
print('Seu último nome é {}'.format(nomen[-1]))